### ISSUE TITLE
feat(label): requests from IvanFon's repo need working on

### ISSUE THREAD

**Issue by TGTGamer** [Videndum/action-masterminds#13]
### My feature request explained

Merge all current open proposals on IvanFon

- [x] Condition for pending reviews (https://github.com/IvanFon/super-labeler-action/issues/6)
- [x] Condition for reviews requested changes
- [x] Condition for reviews approved
- [ ] Syntax for complex combinations of conditions (https://github.com/IvanFon/super-labeler-action/issues/7)
- [x] Able to run, test and debug action locally (https://github.com/IvanFon/super-labeler-action/pull/22 && https://github.com/IvanFon/super-labeler-action/issues/10)
- [x] Check PR size and add a proper label (https://github.com/IvanFon/super-labeler-action/issues/12)
- [ ] Allow adding fallback if no label match occurs (https://github.com/IvanFon/super-labeler-action/issues/13)
